# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Persone'},
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='indirizzo',
            new_name='nominativo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
    ]
