# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrica', '0002_auto_20160921_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nominativo',
        ),
        migrations.AddField(
            model_name='persona',
            name='cognome',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nome',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
